### PR TITLE
Run test on all matrix

### PR DESCRIPTION
**Pull request by fisker**

### CODE REVIEW

**Comment by alexander-akait** [comment]
Still broken :disappointed:

**Comment by fisker** [comment]
The Prettier repo has the same bug on macos 

https://github.com/fisker/prettier/runs/956552801?check_suite_focus=true#step:7:30

**Comment by fisker** [comment]
I don't have a mac book to test it.

The related npm issue is still open https://github.com/npm/cli/issues/1264.

But the issue in `pre-commit` is fixed https://github.com/pre-commit/pre-commit/issues/1440

So, I'm not really sure if user on macOS can use it, or do they know how to fix.

**Comment by fisker** [comment]
Closing this to remove `test-all` branch, another one from my fork #9

**Pull request closed without merging**
